### ISSUE TITLE
Nice effort, but...

### ISSUE THREAD

**Issue by OFark** [chingucoding/IndentRainbow#2]
You got that out quick, well done. However, the "Rainbow" colours, whilst part of the title of the project, are distracting on a dark theme.

Your project of inspiration has a feature where you can edit the colours in json file, that would be much appreciated. As it is I can't use it, just too distracting.

**Comment by chingucoding** [comment]
Hey, thanks for the feedback !
Getting settings to work is currently my main priority, however getting settings to work (VS Option Pages) has been quite a hassle, so it might take a couple more days until it's ready.
In the mean time, I can provide you with a modified VSIX (Visual studio extension) with less distracting colors, if that helps you :)

**Comment by OFark** [comment]
Thank you, I await the next release. Best of luck.

**Comment by chingucoding** [comment]
I finally have been able to implement options and released the new version to the marketplace. 
The way you currently can customize the colors is not optimal, but it works. Improving the way you can customize the colors, is definitely is a long term goal but currently has a very low priority.
If there is anything wrong with the options feel free to reopen this issue :)

**Comment by OFark** [comment]
A swing and a miss...
I can't install it now: 
Install Error : Microsoft.VisualStudio.ExtensionManager.InstallByMsiException: The InstalledByMSI element in extension IndentRainbow cannot be 'true' when installing an extension through the Extensions and Updates Installer.  The element can only be 'true' when an MSI lays down the extension manifest file.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.ExtensionRequiresAdditionalOperationForInstall(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, InstallFlags flags, Boolean& performExtensionUpdate)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by chingucoding** [comment]
Which version of Visual Studio are you using?
And have you tried to update/upgrade from 0.1 to 0.2 are did you try "fresh" install the new version?

**Comment by OFark** [comment]
2017 professional. As of today I have no new VS updates to install.

It was a fresh install. Both from the extensions manager in VS. And as a download from the website.

**Comment by chingucoding** [comment]
Okay. I think i know where the problem is and I'll fix this issue as soon as am back home.

**Comment by chingucoding** [comment]
The bug should now be fixed :)
